//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGSvcClient.PGSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inputs", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class Inputs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AgeLowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AgeUpperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BodyMassIndexLowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BodyMassIndexUpperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.DatasetName DatasetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.EnzymeRateParameterType EnzymeRateParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.EnzymeRateUnitType EnzymeRateUnitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EthnicityProbabilityBlackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EthnicityProbabilityNonBlackOrWhiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EthnicityProbabilityWhiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.FlowUnitType FlowUnitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HeightLowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HeightUpperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.InVitroEnzymeRate[] InVitroEnzymeRatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.RichlyPerfused IsRichlyPerfusedTissueDiscreteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.SlowlyPerfused IsSlowlyPerfusedTissueDiscreteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MolecularWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PopGenUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PopulationSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.PopulationType PopulationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ProbabilityOfMaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AgeLower {
            get {
                return this.AgeLowerField;
            }
            set {
                if ((this.AgeLowerField.Equals(value) != true)) {
                    this.AgeLowerField = value;
                    this.RaisePropertyChanged("AgeLower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AgeUpper {
            get {
                return this.AgeUpperField;
            }
            set {
                if ((this.AgeUpperField.Equals(value) != true)) {
                    this.AgeUpperField = value;
                    this.RaisePropertyChanged("AgeUpper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BodyMassIndexLower {
            get {
                return this.BodyMassIndexLowerField;
            }
            set {
                if ((this.BodyMassIndexLowerField.Equals(value) != true)) {
                    this.BodyMassIndexLowerField = value;
                    this.RaisePropertyChanged("BodyMassIndexLower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BodyMassIndexUpper {
            get {
                return this.BodyMassIndexUpperField;
            }
            set {
                if ((this.BodyMassIndexUpperField.Equals(value) != true)) {
                    this.BodyMassIndexUpperField = value;
                    this.RaisePropertyChanged("BodyMassIndexUpper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.DatasetName Dataset {
            get {
                return this.DatasetField;
            }
            set {
                if ((this.DatasetField.Equals(value) != true)) {
                    this.DatasetField = value;
                    this.RaisePropertyChanged("Dataset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.EnzymeRateParameterType EnzymeRateParameter {
            get {
                return this.EnzymeRateParameterField;
            }
            set {
                if ((this.EnzymeRateParameterField.Equals(value) != true)) {
                    this.EnzymeRateParameterField = value;
                    this.RaisePropertyChanged("EnzymeRateParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.EnzymeRateUnitType EnzymeRateUnits {
            get {
                return this.EnzymeRateUnitsField;
            }
            set {
                if ((this.EnzymeRateUnitsField.Equals(value) != true)) {
                    this.EnzymeRateUnitsField = value;
                    this.RaisePropertyChanged("EnzymeRateUnits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EthnicityProbabilityBlack {
            get {
                return this.EthnicityProbabilityBlackField;
            }
            set {
                if ((this.EthnicityProbabilityBlackField.Equals(value) != true)) {
                    this.EthnicityProbabilityBlackField = value;
                    this.RaisePropertyChanged("EthnicityProbabilityBlack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EthnicityProbabilityNonBlackOrWhite {
            get {
                return this.EthnicityProbabilityNonBlackOrWhiteField;
            }
            set {
                if ((this.EthnicityProbabilityNonBlackOrWhiteField.Equals(value) != true)) {
                    this.EthnicityProbabilityNonBlackOrWhiteField = value;
                    this.RaisePropertyChanged("EthnicityProbabilityNonBlackOrWhite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EthnicityProbabilityWhite {
            get {
                return this.EthnicityProbabilityWhiteField;
            }
            set {
                if ((this.EthnicityProbabilityWhiteField.Equals(value) != true)) {
                    this.EthnicityProbabilityWhiteField = value;
                    this.RaisePropertyChanged("EthnicityProbabilityWhite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.FlowUnitType FlowUnits {
            get {
                return this.FlowUnitsField;
            }
            set {
                if ((this.FlowUnitsField.Equals(value) != true)) {
                    this.FlowUnitsField = value;
                    this.RaisePropertyChanged("FlowUnits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HeightLower {
            get {
                return this.HeightLowerField;
            }
            set {
                if ((this.HeightLowerField.Equals(value) != true)) {
                    this.HeightLowerField = value;
                    this.RaisePropertyChanged("HeightLower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HeightUpper {
            get {
                return this.HeightUpperField;
            }
            set {
                if ((this.HeightUpperField.Equals(value) != true)) {
                    this.HeightUpperField = value;
                    this.RaisePropertyChanged("HeightUpper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.InVitroEnzymeRate[] InVitroEnzymeRates {
            get {
                return this.InVitroEnzymeRatesField;
            }
            set {
                if ((object.ReferenceEquals(this.InVitroEnzymeRatesField, value) != true)) {
                    this.InVitroEnzymeRatesField = value;
                    this.RaisePropertyChanged("InVitroEnzymeRates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.RichlyPerfused IsRichlyPerfusedTissueDiscrete {
            get {
                return this.IsRichlyPerfusedTissueDiscreteField;
            }
            set {
                if ((this.IsRichlyPerfusedTissueDiscreteField.Equals(value) != true)) {
                    this.IsRichlyPerfusedTissueDiscreteField = value;
                    this.RaisePropertyChanged("IsRichlyPerfusedTissueDiscrete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.SlowlyPerfused IsSlowlyPerfusedTissueDiscrete {
            get {
                return this.IsSlowlyPerfusedTissueDiscreteField;
            }
            set {
                if ((this.IsSlowlyPerfusedTissueDiscreteField.Equals(value) != true)) {
                    this.IsSlowlyPerfusedTissueDiscreteField = value;
                    this.RaisePropertyChanged("IsSlowlyPerfusedTissueDiscrete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MolecularWeight {
            get {
                return this.MolecularWeightField;
            }
            set {
                if ((this.MolecularWeightField.Equals(value) != true)) {
                    this.MolecularWeightField = value;
                    this.RaisePropertyChanged("MolecularWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PopGenUserName {
            get {
                return this.PopGenUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PopGenUserNameField, value) != true)) {
                    this.PopGenUserNameField = value;
                    this.RaisePropertyChanged("PopGenUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PopulationSize {
            get {
                return this.PopulationSizeField;
            }
            set {
                if ((this.PopulationSizeField.Equals(value) != true)) {
                    this.PopulationSizeField = value;
                    this.RaisePropertyChanged("PopulationSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.PopulationType PopulationType {
            get {
                return this.PopulationTypeField;
            }
            set {
                if ((this.PopulationTypeField.Equals(value) != true)) {
                    this.PopulationTypeField = value;
                    this.RaisePropertyChanged("PopulationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ProbabilityOfMale {
            get {
                return this.ProbabilityOfMaleField;
            }
            set {
                if ((this.ProbabilityOfMaleField.Equals(value) != true)) {
                    this.ProbabilityOfMaleField = value;
                    this.RaisePropertyChanged("ProbabilityOfMale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Seed {
            get {
                return this.SeedField;
            }
            set {
                if ((this.SeedField.Equals(value) != true)) {
                    this.SeedField = value;
                    this.RaisePropertyChanged("Seed");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatasetName", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGType")]
    public enum DatasetName : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        @__None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        P3M = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ICRP = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HSE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NDNS = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnzymeRateParameterType", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGType")]
    public enum EnzymeRateParameterType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        @__None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vmax = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLint = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnzymeRateUnitType", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGType")]
    public enum EnzymeRateUnitType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        @__None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PicoMolsPerMinute = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MicroMolsPerHour = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MilliMolsPerHour = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PicoGramsPerMinute = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MicroGramsPerHour = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MilliGramsPerHour = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MicroLitresPerMinute = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MilliLitresPerHour = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LitresPerHour = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlowUnitType", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGType")]
    public enum FlowUnitType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        @__None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MilliLitresPerMinute = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LitresPerHour = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InVitroEnzymeRate", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class InVitroEnzymeRate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnzymeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Enzyme {
            get {
                return this.EnzymeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnzymeField, value) != true)) {
                    this.EnzymeField = value;
                    this.RaisePropertyChanged("Enzyme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="RichlyPerfused", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGType")]
    public enum RichlyPerfused : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Brain = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gonads = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Heart = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kidney = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LargeIntestine = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Liver = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pancreas = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmallIntestine = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spleen = 256,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stomach = 512,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="SlowlyPerfused", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGType")]
    public enum SlowlyPerfused : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Adipose = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bone = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Muscle = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Skin = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PopulationType", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGType")]
    public enum PopulationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        @__None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Realistic = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HighVariation = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PopGenFault", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGSvc")]
    [System.SerializableAttribute()]
    public partial class PopGenFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PopGenRes", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class PopGenRes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Individual[] IndividualsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Parameters ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Summary SummaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Individual[] Individuals {
            get {
                return this.IndividualsField;
            }
            set {
                if ((object.ReferenceEquals(this.IndividualsField, value) != true)) {
                    this.IndividualsField = value;
                    this.RaisePropertyChanged("Individuals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Parameters Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Summary Summary {
            get {
                return this.SummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.SummaryField, value) != true)) {
                    this.SummaryField = value;
                    this.RaisePropertyChanged("Summary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parameters", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class Parameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Filter FilterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Population PopulationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Probability ProbabilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Units UnitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Filter Filter {
            get {
                return this.FilterField;
            }
            set {
                if ((object.ReferenceEquals(this.FilterField, value) != true)) {
                    this.FilterField = value;
                    this.RaisePropertyChanged("Filter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Population Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((object.ReferenceEquals(this.PopulationField, value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Probability Probability {
            get {
                return this.ProbabilityField;
            }
            set {
                if ((object.ReferenceEquals(this.ProbabilityField, value) != true)) {
                    this.ProbabilityField = value;
                    this.RaisePropertyChanged("Probability");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Units Units {
            get {
                return this.UnitsField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitsField, value) != true)) {
                    this.UnitsField = value;
                    this.RaisePropertyChanged("Units");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Summary", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class Summary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.SummaryStats FemaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.SummaryStats MaleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.SummaryStats Female {
            get {
                return this.FemaleField;
            }
            set {
                if ((object.ReferenceEquals(this.FemaleField, value) != true)) {
                    this.FemaleField = value;
                    this.RaisePropertyChanged("Female");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.SummaryStats Male {
            get {
                return this.MaleField;
            }
            set {
                if ((object.ReferenceEquals(this.MaleField, value) != true)) {
                    this.MaleField = value;
                    this.RaisePropertyChanged("Male");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Individual", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class Individual : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BodyMassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CardiacOutputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Enzymes EnzymesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Ethnicity EthnicityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Sex SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Tissue[] TissuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BodyMass {
            get {
                return this.BodyMassField;
            }
            set {
                if ((this.BodyMassField.Equals(value) != true)) {
                    this.BodyMassField = value;
                    this.RaisePropertyChanged("BodyMass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CardiacOutput {
            get {
                return this.CardiacOutputField;
            }
            set {
                if ((this.CardiacOutputField.Equals(value) != true)) {
                    this.CardiacOutputField = value;
                    this.RaisePropertyChanged("CardiacOutput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Enzymes Enzymes {
            get {
                return this.EnzymesField;
            }
            set {
                if ((object.ReferenceEquals(this.EnzymesField, value) != true)) {
                    this.EnzymesField = value;
                    this.RaisePropertyChanged("Enzymes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Ethnicity Ethnicity {
            get {
                return this.EthnicityField;
            }
            set {
                if ((this.EthnicityField.Equals(value) != true)) {
                    this.EthnicityField = value;
                    this.RaisePropertyChanged("Ethnicity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Sex Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Tissue[] Tissues {
            get {
                return this.TissuesField;
            }
            set {
                if ((object.ReferenceEquals(this.TissuesField, value) != true)) {
                    this.TissuesField = value;
                    this.RaisePropertyChanged("Tissues");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enzymes", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class Enzymes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Enzyme[] EnzymeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MppglField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Enzyme[] Enzyme {
            get {
                return this.EnzymeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnzymeField, value) != true)) {
                    this.EnzymeField = value;
                    this.RaisePropertyChanged("Enzyme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mppgl {
            get {
                return this.MppglField;
            }
            set {
                if ((this.MppglField.Equals(value) != true)) {
                    this.MppglField = value;
                    this.RaisePropertyChanged("Mppgl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ethnicity", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGType")]
    public enum Ethnicity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        @__None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        White = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Black = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NonBlackOrWhite = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sex", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGType")]
    public enum Sex : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        @__None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tissue", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class Tissue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FlowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Flow {
            get {
                return this.FlowField;
            }
            set {
                if ((this.FlowField.Equals(value) != true)) {
                    this.FlowField = value;
                    this.RaisePropertyChanged("Flow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mass {
            get {
                return this.MassField;
            }
            set {
                if ((this.MassField.Equals(value) != true)) {
                    this.MassField = value;
                    this.RaisePropertyChanged("Mass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enzyme", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class Enzyme : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InVivoEnzymeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InVivoEnzymeRate {
            get {
                return this.InVivoEnzymeRateField;
            }
            set {
                if ((this.InVivoEnzymeRateField.Equals(value) != true)) {
                    this.InVivoEnzymeRateField = value;
                    this.RaisePropertyChanged("InVivoEnzymeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filter", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class Filter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AgeLowerLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AgeUpperLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BmiLowerLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BmiUpperLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HeightLowerLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HeightUpperLimitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AgeLowerLimit {
            get {
                return this.AgeLowerLimitField;
            }
            set {
                if ((this.AgeLowerLimitField.Equals(value) != true)) {
                    this.AgeLowerLimitField = value;
                    this.RaisePropertyChanged("AgeLowerLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AgeUpperLimit {
            get {
                return this.AgeUpperLimitField;
            }
            set {
                if ((this.AgeUpperLimitField.Equals(value) != true)) {
                    this.AgeUpperLimitField = value;
                    this.RaisePropertyChanged("AgeUpperLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BmiLowerLimit {
            get {
                return this.BmiLowerLimitField;
            }
            set {
                if ((this.BmiLowerLimitField.Equals(value) != true)) {
                    this.BmiLowerLimitField = value;
                    this.RaisePropertyChanged("BmiLowerLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BmiUpperLimit {
            get {
                return this.BmiUpperLimitField;
            }
            set {
                if ((this.BmiUpperLimitField.Equals(value) != true)) {
                    this.BmiUpperLimitField = value;
                    this.RaisePropertyChanged("BmiUpperLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HeightLowerLimit {
            get {
                return this.HeightLowerLimitField;
            }
            set {
                if ((this.HeightLowerLimitField.Equals(value) != true)) {
                    this.HeightLowerLimitField = value;
                    this.RaisePropertyChanged("HeightLowerLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HeightUpperLimit {
            get {
                return this.HeightUpperLimitField;
            }
            set {
                if ((this.HeightUpperLimitField.Equals(value) != true)) {
                    this.HeightUpperLimitField = value;
                    this.RaisePropertyChanged("HeightUpperLimit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Population", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class Population : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatasetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dataset {
            get {
                return this.DatasetField;
            }
            set {
                if ((object.ReferenceEquals(this.DatasetField, value) != true)) {
                    this.DatasetField = value;
                    this.RaisePropertyChanged("Dataset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Seed {
            get {
                return this.SeedField;
            }
            set {
                if ((this.SeedField.Equals(value) != true)) {
                    this.SeedField = value;
                    this.RaisePropertyChanged("Seed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Probability", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class Probability : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EthnicityBlackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EthnicityNonBlackOrWhiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EthnicityWhiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EthnicityBlack {
            get {
                return this.EthnicityBlackField;
            }
            set {
                if ((this.EthnicityBlackField.Equals(value) != true)) {
                    this.EthnicityBlackField = value;
                    this.RaisePropertyChanged("EthnicityBlack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EthnicityNonBlackOrWhite {
            get {
                return this.EthnicityNonBlackOrWhiteField;
            }
            set {
                if ((this.EthnicityNonBlackOrWhiteField.Equals(value) != true)) {
                    this.EthnicityNonBlackOrWhiteField = value;
                    this.RaisePropertyChanged("EthnicityNonBlackOrWhite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EthnicityWhite {
            get {
                return this.EthnicityWhiteField;
            }
            set {
                if ((this.EthnicityWhiteField.Equals(value) != true)) {
                    this.EthnicityWhiteField = value;
                    this.RaisePropertyChanged("EthnicityWhite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Male {
            get {
                return this.MaleField;
            }
            set {
                if ((this.MaleField.Equals(value) != true)) {
                    this.MaleField = value;
                    this.RaisePropertyChanged("Male");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Units", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class Units : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnzymeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlowField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnzymeRate {
            get {
                return this.EnzymeRateField;
            }
            set {
                if ((object.ReferenceEquals(this.EnzymeRateField, value) != true)) {
                    this.EnzymeRateField = value;
                    this.RaisePropertyChanged("EnzymeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Flow {
            get {
                return this.FlowField;
            }
            set {
                if ((object.ReferenceEquals(this.FlowField, value) != true)) {
                    this.FlowField = value;
                    this.RaisePropertyChanged("Flow");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SummaryStats", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class SummaryStats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Stats[] FlowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Stats[] InVivoEnzymeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Stats[] MassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PGSvcClient.PGSvc.Stats[] MppglField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Stats[] Flow {
            get {
                return this.FlowField;
            }
            set {
                if ((object.ReferenceEquals(this.FlowField, value) != true)) {
                    this.FlowField = value;
                    this.RaisePropertyChanged("Flow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Stats[] InVivoEnzymeRate {
            get {
                return this.InVivoEnzymeRateField;
            }
            set {
                if ((object.ReferenceEquals(this.InVivoEnzymeRateField, value) != true)) {
                    this.InVivoEnzymeRateField = value;
                    this.RaisePropertyChanged("InVivoEnzymeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Stats[] Mass {
            get {
                return this.MassField;
            }
            set {
                if ((object.ReferenceEquals(this.MassField, value) != true)) {
                    this.MassField = value;
                    this.RaisePropertyChanged("Mass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PGSvcClient.PGSvc.Stats[] Mppgl {
            get {
                return this.MppglField;
            }
            set {
                if ((object.ReferenceEquals(this.MppglField, value) != true)) {
                    this.MppglField = value;
                    this.RaisePropertyChanged("Mppgl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stats", Namespace="urn:uk-gov-hsl-msu:pgsvc-v03")]
    [System.SerializableAttribute()]
    public partial class Stats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GeoMeanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double GeoStdDevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MeanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MedianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double P2pt5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double P5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double P95Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double P97pt5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double StdDevField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GeoMean {
            get {
                return this.GeoMeanField;
            }
            set {
                if ((this.GeoMeanField.Equals(value) != true)) {
                    this.GeoMeanField = value;
                    this.RaisePropertyChanged("GeoMean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GeoStdDev {
            get {
                return this.GeoStdDevField;
            }
            set {
                if ((this.GeoStdDevField.Equals(value) != true)) {
                    this.GeoStdDevField = value;
                    this.RaisePropertyChanged("GeoStdDev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mean {
            get {
                return this.MeanField;
            }
            set {
                if ((this.MeanField.Equals(value) != true)) {
                    this.MeanField = value;
                    this.RaisePropertyChanged("Mean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Median {
            get {
                return this.MedianField;
            }
            set {
                if ((this.MedianField.Equals(value) != true)) {
                    this.MedianField = value;
                    this.RaisePropertyChanged("Median");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double P2pt5 {
            get {
                return this.P2pt5Field;
            }
            set {
                if ((this.P2pt5Field.Equals(value) != true)) {
                    this.P2pt5Field = value;
                    this.RaisePropertyChanged("P2pt5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double P5 {
            get {
                return this.P5Field;
            }
            set {
                if ((this.P5Field.Equals(value) != true)) {
                    this.P5Field = value;
                    this.RaisePropertyChanged("P5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double P95 {
            get {
                return this.P95Field;
            }
            set {
                if ((this.P95Field.Equals(value) != true)) {
                    this.P95Field = value;
                    this.RaisePropertyChanged("P95");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double P97pt5 {
            get {
                return this.P97pt5Field;
            }
            set {
                if ((this.P97pt5Field.Equals(value) != true)) {
                    this.P97pt5Field = value;
                    this.RaisePropertyChanged("P97pt5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double StdDev {
            get {
                return this.StdDevField;
            }
            set {
                if ((this.StdDevField.Equals(value) != true)) {
                    this.StdDevField = value;
                    this.RaisePropertyChanged("StdDev");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:uk-gov-hsl-msu:pgsvc-v03", ConfigurationName="PGSvc.PopGenSvc", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface PopGenSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/Generate", ReplyAction="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/GenerateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PGSvcClient.PGSvc.PopGenFault), Action="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/GeneratePopGenFaultFault", Name="PopGenFault", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGSvc")]
        string[] Generate(PGSvcClient.PGSvc.Inputs inputs);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/Cancel", ReplyAction="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/CancelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PGSvcClient.PGSvc.PopGenFault), Action="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/CancelPopGenFaultFault", Name="PopGenFault", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGSvc")]
        int Cancel();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/IsCompleted", ReplyAction="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/IsCompletedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PGSvcClient.PGSvc.PopGenFault), Action="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/IsCompletedPopGenFaultFault", Name="PopGenFault", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGSvc")]
        bool IsCompleted();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/RetrieveResults", ReplyAction="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/RetrieveResultsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PGSvcClient.PGSvc.PopGenFault), Action="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/RetrieveResultsPopGenFaultFault", Name="PopGenFault", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGSvc")]
        PGSvcClient.PGSvc.PopGenRes RetrieveResults();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/CleanUp", ReplyAction="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/CleanUpResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PGSvcClient.PGSvc.PopGenFault), Action="urn:uk-gov-hsl-msu:pgsvc-v03/PopGenSvc/CleanUpPopGenFaultFault", Name="PopGenFault", Namespace="http://schemas.datacontract.org/2004/07/UK.Gov.Hsl.Msu.PGSvc")]
        int CleanUp();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PopGenSvcChannel : PGSvcClient.PGSvc.PopGenSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PopGenSvcClient : System.ServiceModel.ClientBase<PGSvcClient.PGSvc.PopGenSvc>, PGSvcClient.PGSvc.PopGenSvc {
        
        public PopGenSvcClient() {
        }
        
        public PopGenSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PopGenSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PopGenSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PopGenSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Generate(PGSvcClient.PGSvc.Inputs inputs) {
            return base.Channel.Generate(inputs);
        }
        
        public int Cancel() {
            return base.Channel.Cancel();
        }
        
        public bool IsCompleted() {
            return base.Channel.IsCompleted();
        }
        
        public PGSvcClient.PGSvc.PopGenRes RetrieveResults() {
            return base.Channel.RetrieveResults();
        }
        
        public int CleanUp() {
            return base.Channel.CleanUp();
        }
    }
}
